# Generated by Django 4.1.3 on 2022-12-15 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customers_credits_customers_joiningdate_and_more'),
        ('products', '0002_productstable_producttypetable_and_more'),
        ('reportsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('orderid', models.IntegerField(primary_key=True, serialize=False)),
                ('orderDate', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customers')),
            ],
        ),
        migrations.CreateModel(
            name='productanalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producttype', models.CharField(max_length=20)),
                ('sales', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='saleslist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportsapp.orders')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productstable')),
                ('producttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.producttypetable', to_field='producttype')),
            ],
            options={
                'unique_together': {('orderid', 'productid')},
            },
        ),
    ]
