# Generated by Django 3.2.16 on 2022-11-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projectcrmapptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('thiruvalla', models.CharField(max_length=200)),
                ('kottayam', models.CharField(max_length=200)),
                ('kochi', models.CharField(max_length=200)),
                ('img', models.CharField(max_length=200)),
            ],
        ),
    ]
