# Generated by Django 4.1.3 on 2022-11-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectcrmapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productstable',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('thiruvalla', models.IntegerField()),
                ('kottayam', models.IntegerField()),
                ('kochi', models.IntegerField()),
                ('img', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='projectcrmapptable',
        ),
    ]
