# Generated by Django 3.2.16 on 2022-11-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectcrmapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcrmapptable',
            name='kochi',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='projectcrmapptable',
            name='kottayam',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='projectcrmapptable',
            name='thiruvalla',
            field=models.IntegerField(max_length=200),
        ),
    ]
