# Generated by Django 3.2.16 on 2022-11-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectcrmapp', '0002_auto_20221124_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcrmapptable',
            name='kochi',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='projectcrmapptable',
            name='kottayam',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='projectcrmapptable',
            name='thiruvalla',
            field=models.IntegerField(),
        ),
    ]
