# Generated by Django 4.1.3 on 2022-12-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectcrmapp', '0002_productstable_delete_projectcrmapptable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstable',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
