# Generated by Django 3.2.16 on 2022-11-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectcrmapp', '0003_auto_20221124_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='productstable',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('thiruvalla', models.IntegerField()),
                ('kottayam', models.IntegerField()),
                ('kochi', models.IntegerField()),
                ('img', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='projectcrmapptable',
        ),
    ]
