# Generated by Django 4.1.3 on 2022-12-08 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectcrmapp', '0002_productstable_producttypetable_and_more'),
        ('offerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offertable',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectcrmapp.productstable', to_field='title'),
        ),
        migrations.AlterField(
            model_name='offertable',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectcrmapp.producttypetable', to_field='producttype'),
        ),
    ]
