# Generated by Django 4.1.3 on 2022-12-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerapp', '0002_alter_offertable_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='specialoffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.TextField()),
            ],
        ),
    ]
