# Generated by Django 4.1.3 on 2022-12-15 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_customers_credits_customers_joiningdate_and_more'),
        ('products', '0002_productstable_producttypetable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='supportlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supporttype', models.CharField(max_length=200)),
                ('remarks', models.TextField()),
                ('status', models.CharField(max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customers')),
                ('productname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productstable', to_field='title')),
            ],
        ),
    ]
