# Generated by Django 4.1.3 on 2022-12-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='analysis_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderID', models.BigIntegerField()),
                ('Product', models.TextField()),
                ('QuantityOrdered', models.BigIntegerField()),
                ('PriceEach', models.FloatField()),
                ('OrderDate', models.TextField()),
                ('PurchaseAddress', models.TextField()),
            ],
            options={
                'db_table': 'analysis_data',
                'managed': False,
            },
        ),
    ]
