# Generated by Django 4.1.3 on 2022-12-09 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysisapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='analysis_data',
        ),
    ]
