# Generated by Django 4.1.3 on 2022-12-15 18:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productstable_producttypetable_and_more'),
        ('offerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='specialoffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.TextField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('minCredits', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='offertable',
            name='endDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offertable',
            name='startDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offertable',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productstable', to_field='title'),
        ),
        migrations.AlterField(
            model_name='offertable',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.producttypetable', to_field='producttype'),
        ),
    ]
