# Generated by Django 4.1.3 on 2022-12-15 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customers',
            name='joiningDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customers',
            name='premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customers',
            name='PhoneNumber',
            field=models.BigIntegerField(),
        ),
    ]
