# Generated by Django 4.1.3 on 2022-11-25 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_customers_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='joiningDate',
            field=models.DateField(default=datetime.datetime(2022, 11, 25, 7, 20, 34, 881623, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
