# Generated by Django 4.1.3 on 2022-11-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_customers_joiningdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='customerOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.IntegerField()),
                ('Amount', models.IntegerField()),
                ('ProductId', models.IntegerField()),
                ('ProductName', models.CharField(max_length=200)),
            ],
        ),
    ]
