# Generated by Django 4.1.3 on 2022-11-24 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_customers_joiningdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='joiningDate',
        ),
    ]
