# Generated by Django 3.1.4 on 2022-11-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_remove_customers_joiningdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
