# Generated by Django 4.1.3 on 2022-11-28 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_customerorders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customerOrders',
        ),
    ]
