# Generated by Django 4.1.3 on 2022-11-29 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projectcrmapp', '0002_productstable_delete_projectcrmapptable'),
        ('crm', '0005_delete_customerorders'),
    ]

    operations = [
        migrations.CreateModel(
            name='supportlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supporttype', models.CharField(max_length=200)),
                ('remarks', models.TextField()),
                ('status', models.CharField(max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customers')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectcrmapp.productstable')),
            ],
        ),
    ]
