# Generated by Django 4.1.3 on 2022-12-03 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectcrmapp', '0003_alter_productstable_title'),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportlist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectcrmapp.productstable', to_field='title'),
        ),
    ]
