# Generated by Django 4.1.3 on 2022-12-02 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportsapp', '0003_customerorders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customerOrders',
        ),
    ]
