# Generated by Django 4.1.3 on 2022-11-29 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportsapp', '0004_customerorders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customerOrders',
        ),
    ]
